version: "3"

services:
  banner:
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: banner-app
    environment:
      DB_HOST: ${POSTGRES_HOST:-postgres}
      SERVER_PORT: 8081
      SERVER_ISHTTP: true
      KAFKA_BROKERS: "kafka:29092"
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
      - banner-network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-banner} # имя БД
      POSTGRES_USER: ${POSTGRES_USER:-user} # пользователь
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # пароль
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d banner" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_banner_data:/var/lib/postgresql/data
    networks:
      - banner-network

  migrate:
    build:
      context: ..
      dockerfile: build/goose/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://user:password@postgres:5432/banner"
      GOOSE_MIGRATION_DIR: "./migrations"
      GOOSE_TABLE: "goose_migrations"
    volumes:
      - ../migrations:/migrations
    command: ["goose", "up"]
    networks:
      - banner-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"  # внутренний порт для взаимодействия между контейнерами
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "ZHVtbXktY2x1c3Rlci1pZA==" # кастомный ID, можно любой UUID
    volumes:
      - /tmp/kraft-logs:/tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - banner-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - banner-network

networks:
  banner-network:
    driver: bridge

volumes:
  postgres_banner_data:
  kafka-data: