// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: BannerService.proto

package internalgrpcprotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAddSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAddSlot) Reset() {
	*x = RequestAddSlot{}
	mi := &file_BannerService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAddSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddSlot) ProtoMessage() {}

func (x *RequestAddSlot) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddSlot.ProtoReflect.Descriptor instead.
func (*RequestAddSlot) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAddSlot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RequestGetSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetSlot) Reset() {
	*x = RequestGetSlot{}
	mi := &file_BannerService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetSlot) ProtoMessage() {}

func (x *RequestGetSlot) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetSlot.ProtoReflect.Descriptor instead.
func (*RequestGetSlot) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGetSlot) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseSlot) Reset() {
	*x = ResponseSlot{}
	mi := &file_BannerService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSlot) ProtoMessage() {}

func (x *ResponseSlot) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSlot.ProtoReflect.Descriptor instead.
func (*ResponseSlot) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseSlot) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ResponseSlot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseSlot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RequestAddBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAddBanner) Reset() {
	*x = RequestAddBanner{}
	mi := &file_BannerService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAddBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddBanner) ProtoMessage() {}

func (x *RequestAddBanner) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddBanner.ProtoReflect.Descriptor instead.
func (*RequestAddBanner) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{3}
}

func (x *RequestAddBanner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestAddBanner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RequestGetBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetBanner) Reset() {
	*x = RequestGetBanner{}
	mi := &file_BannerService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetBanner) ProtoMessage() {}

func (x *RequestGetBanner) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetBanner.ProtoReflect.Descriptor instead.
func (*RequestGetBanner) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{4}
}

func (x *RequestGetBanner) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBanner) Reset() {
	*x = ResponseBanner{}
	mi := &file_BannerService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBanner) ProtoMessage() {}

func (x *ResponseBanner) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBanner.ProtoReflect.Descriptor instead.
func (*ResponseBanner) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseBanner) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ResponseBanner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResponseBanner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseBanner) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RequestAddGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAddGroup) Reset() {
	*x = RequestAddGroup{}
	mi := &file_BannerService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAddGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddGroup) ProtoMessage() {}

func (x *RequestAddGroup) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddGroup.ProtoReflect.Descriptor instead.
func (*RequestAddGroup) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{6}
}

func (x *RequestAddGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestAddGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RequestGetGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetGroup) Reset() {
	*x = RequestGetGroup{}
	mi := &file_BannerService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetGroup) ProtoMessage() {}

func (x *RequestGetGroup) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetGroup.ProtoReflect.Descriptor instead.
func (*RequestGetGroup) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{7}
}

func (x *RequestGetGroup) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGroup) Reset() {
	*x = ResponseGroup{}
	mi := &file_BannerService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGroup) ProtoMessage() {}

func (x *ResponseGroup) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGroup.ProtoReflect.Descriptor instead.
func (*ResponseGroup) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseGroup) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ResponseGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResponseGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseGroup) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RequestAddBannerGroupStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotID        int64                  `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID      int64                  `protobuf:"varint,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	GroupID       int64                  `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAddBannerGroupStats) Reset() {
	*x = RequestAddBannerGroupStats{}
	mi := &file_BannerService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAddBannerGroupStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddBannerGroupStats) ProtoMessage() {}

func (x *RequestAddBannerGroupStats) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddBannerGroupStats.ProtoReflect.Descriptor instead.
func (*RequestAddBannerGroupStats) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{9}
}

func (x *RequestAddBannerGroupStats) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *RequestAddBannerGroupStats) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *RequestAddBannerGroupStats) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type RequestGetBannerGroupStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotID        int64                  `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID      int64                  `protobuf:"varint,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	GroupID       int64                  `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetBannerGroupStats) Reset() {
	*x = RequestGetBannerGroupStats{}
	mi := &file_BannerService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetBannerGroupStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetBannerGroupStats) ProtoMessage() {}

func (x *RequestGetBannerGroupStats) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetBannerGroupStats.ProtoReflect.Descriptor instead.
func (*RequestGetBannerGroupStats) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{10}
}

func (x *RequestGetBannerGroupStats) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *RequestGetBannerGroupStats) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *RequestGetBannerGroupStats) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type ResponseBannerGroupStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SlotID        int64                  `protobuf:"varint,2,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID      int64                  `protobuf:"varint,3,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	GroupID       int64                  `protobuf:"varint,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Shows         int64                  `protobuf:"varint,5,opt,name=Shows,proto3" json:"Shows,omitempty"`
	Clicks        int64                  `protobuf:"varint,6,opt,name=Clicks,proto3" json:"Clicks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBannerGroupStats) Reset() {
	*x = ResponseBannerGroupStats{}
	mi := &file_BannerService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBannerGroupStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBannerGroupStats) ProtoMessage() {}

func (x *ResponseBannerGroupStats) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBannerGroupStats.ProtoReflect.Descriptor instead.
func (*ResponseBannerGroupStats) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseBannerGroupStats) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetShows() int64 {
	if x != nil {
		return x.Shows
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *ResponseBannerGroupStats) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseBannerGroupStats) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RequestRegisterClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotID        int64                  `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID      int64                  `protobuf:"varint,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	GroupID       int64                  `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRegisterClick) Reset() {
	*x = RequestRegisterClick{}
	mi := &file_BannerService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRegisterClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRegisterClick) ProtoMessage() {}

func (x *RequestRegisterClick) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRegisterClick.ProtoReflect.Descriptor instead.
func (*RequestRegisterClick) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{12}
}

func (x *RequestRegisterClick) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *RequestRegisterClick) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *RequestRegisterClick) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type ResponseRegisterClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerID      int64                  `protobuf:"varint,1,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRegisterClick) Reset() {
	*x = ResponseRegisterClick{}
	mi := &file_BannerService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRegisterClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRegisterClick) ProtoMessage() {}

func (x *ResponseRegisterClick) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRegisterClick.ProtoReflect.Descriptor instead.
func (*ResponseRegisterClick) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseRegisterClick) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

type RequestGetBannerByMultiArmBandit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotID        int64                  `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	GroupID       int64                  `protobuf:"varint,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetBannerByMultiArmBandit) Reset() {
	*x = RequestGetBannerByMultiArmBandit{}
	mi := &file_BannerService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetBannerByMultiArmBandit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetBannerByMultiArmBandit) ProtoMessage() {}

func (x *RequestGetBannerByMultiArmBandit) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetBannerByMultiArmBandit.ProtoReflect.Descriptor instead.
func (*RequestGetBannerByMultiArmBandit) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{14}
}

func (x *RequestGetBannerByMultiArmBandit) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *RequestGetBannerByMultiArmBandit) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

var File_BannerService_proto protoreflect.FileDescriptor

const file_BannerService_proto_rawDesc = "" +
	"\n" +
	"\x13BannerService.proto\x12\x06banner\"2\n" +
	"\x0eRequestAddSlot\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\" \n" +
	"\x0eRequestGetSlot\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"^\n" +
	"\fResponseSlot\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1c\n" +
	"\tCreatedAt\x18\x03 \x01(\tR\tCreatedAt\"J\n" +
	"\x10RequestAddBanner\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"\"\n" +
	"\x10RequestGetBanner\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"v\n" +
	"\x0eResponseBanner\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1c\n" +
	"\tCreatedAt\x18\x04 \x01(\tR\tCreatedAt\"I\n" +
	"\x0fRequestAddGroup\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"!\n" +
	"\x0fRequestGetGroup\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"u\n" +
	"\rResponseGroup\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1c\n" +
	"\tCreatedAt\x18\x04 \x01(\tR\tCreatedAt\"j\n" +
	"\x1aRequestAddBannerGroupStats\x12\x16\n" +
	"\x06SlotID\x18\x01 \x01(\x03R\x06SlotID\x12\x1a\n" +
	"\bBannerID\x18\x02 \x01(\x03R\bBannerID\x12\x18\n" +
	"\aGroupID\x18\x03 \x01(\x03R\aGroupID\"j\n" +
	"\x1aRequestGetBannerGroupStats\x12\x16\n" +
	"\x06SlotID\x18\x01 \x01(\x03R\x06SlotID\x12\x1a\n" +
	"\bBannerID\x18\x02 \x01(\x03R\bBannerID\x12\x18\n" +
	"\aGroupID\x18\x03 \x01(\x03R\aGroupID\"\xe2\x01\n" +
	"\x18ResponseBannerGroupStats\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06SlotID\x18\x02 \x01(\x03R\x06SlotID\x12\x1a\n" +
	"\bBannerID\x18\x03 \x01(\x03R\bBannerID\x12\x18\n" +
	"\aGroupID\x18\x04 \x01(\x03R\aGroupID\x12\x14\n" +
	"\x05Shows\x18\x05 \x01(\x03R\x05Shows\x12\x16\n" +
	"\x06Clicks\x18\x06 \x01(\x03R\x06Clicks\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\b \x01(\tR\tUpdatedAt\"d\n" +
	"\x14RequestRegisterClick\x12\x16\n" +
	"\x06SlotID\x18\x01 \x01(\x03R\x06SlotID\x12\x1a\n" +
	"\bBannerID\x18\x02 \x01(\x03R\bBannerID\x12\x18\n" +
	"\aGroupID\x18\x03 \x01(\x03R\aGroupID\"3\n" +
	"\x15ResponseRegisterClick\x12\x1a\n" +
	"\bBannerID\x18\x01 \x01(\x03R\bBannerID\"T\n" +
	" RequestGetBannerByMultiArmBandit\x12\x16\n" +
	"\x06SlotID\x18\x01 \x01(\x03R\x06SlotID\x12\x18\n" +
	"\aGroupID\x18\x02 \x01(\x03R\aGroupID2\xde\x05\n" +
	"\rBannerService\x127\n" +
	"\aAddSlot\x12\x16.banner.RequestAddSlot\x1a\x14.banner.ResponseSlot\x127\n" +
	"\aGetSlot\x12\x16.banner.RequestGetSlot\x1a\x14.banner.ResponseSlot\x12=\n" +
	"\tAddBanner\x12\x18.banner.RequestAddBanner\x1a\x16.banner.ResponseBanner\x12=\n" +
	"\tGetBanner\x12\x18.banner.RequestGetBanner\x1a\x16.banner.ResponseBanner\x12:\n" +
	"\bAddGroup\x12\x17.banner.RequestAddGroup\x1a\x15.banner.ResponseGroup\x12:\n" +
	"\bGetGroup\x12\x17.banner.RequestGetGroup\x1a\x15.banner.ResponseGroup\x12[\n" +
	"\x13AddBannerGroupStats\x12\".banner.RequestAddBannerGroupStats\x1a .banner.ResponseBannerGroupStats\x12[\n" +
	"\x13GetBannerGroupStats\x12\".banner.RequestGetBannerGroupStats\x1a .banner.ResponseBannerGroupStats\x12L\n" +
	"\rRegisterClick\x12\x1c.banner.RequestRegisterClick\x1a\x1d.banner.ResponseRegisterClick\x12]\n" +
	"\x19GetBannerByMultiArmBandit\x12(.banner.RequestGetBannerByMultiArmBandit\x1a\x16.banner.ResponseBannerB\x19Z\x17./;internalgrpcprotobufb\x06proto3"

var (
	file_BannerService_proto_rawDescOnce sync.Once
	file_BannerService_proto_rawDescData []byte
)

func file_BannerService_proto_rawDescGZIP() []byte {
	file_BannerService_proto_rawDescOnce.Do(func() {
		file_BannerService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BannerService_proto_rawDesc), len(file_BannerService_proto_rawDesc)))
	})
	return file_BannerService_proto_rawDescData
}

var file_BannerService_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_BannerService_proto_goTypes = []any{
	(*RequestAddSlot)(nil),                   // 0: banner.RequestAddSlot
	(*RequestGetSlot)(nil),                   // 1: banner.RequestGetSlot
	(*ResponseSlot)(nil),                     // 2: banner.ResponseSlot
	(*RequestAddBanner)(nil),                 // 3: banner.RequestAddBanner
	(*RequestGetBanner)(nil),                 // 4: banner.RequestGetBanner
	(*ResponseBanner)(nil),                   // 5: banner.ResponseBanner
	(*RequestAddGroup)(nil),                  // 6: banner.RequestAddGroup
	(*RequestGetGroup)(nil),                  // 7: banner.RequestGetGroup
	(*ResponseGroup)(nil),                    // 8: banner.ResponseGroup
	(*RequestAddBannerGroupStats)(nil),       // 9: banner.RequestAddBannerGroupStats
	(*RequestGetBannerGroupStats)(nil),       // 10: banner.RequestGetBannerGroupStats
	(*ResponseBannerGroupStats)(nil),         // 11: banner.ResponseBannerGroupStats
	(*RequestRegisterClick)(nil),             // 12: banner.RequestRegisterClick
	(*ResponseRegisterClick)(nil),            // 13: banner.ResponseRegisterClick
	(*RequestGetBannerByMultiArmBandit)(nil), // 14: banner.RequestGetBannerByMultiArmBandit
}
var file_BannerService_proto_depIdxs = []int32{
	0,  // 0: banner.BannerService.AddSlot:input_type -> banner.RequestAddSlot
	1,  // 1: banner.BannerService.GetSlot:input_type -> banner.RequestGetSlot
	3,  // 2: banner.BannerService.AddBanner:input_type -> banner.RequestAddBanner
	4,  // 3: banner.BannerService.GetBanner:input_type -> banner.RequestGetBanner
	6,  // 4: banner.BannerService.AddGroup:input_type -> banner.RequestAddGroup
	7,  // 5: banner.BannerService.GetGroup:input_type -> banner.RequestGetGroup
	9,  // 6: banner.BannerService.AddBannerGroupStats:input_type -> banner.RequestAddBannerGroupStats
	10, // 7: banner.BannerService.GetBannerGroupStats:input_type -> banner.RequestGetBannerGroupStats
	12, // 8: banner.BannerService.RegisterClick:input_type -> banner.RequestRegisterClick
	14, // 9: banner.BannerService.GetBannerByMultiArmBandit:input_type -> banner.RequestGetBannerByMultiArmBandit
	2,  // 10: banner.BannerService.AddSlot:output_type -> banner.ResponseSlot
	2,  // 11: banner.BannerService.GetSlot:output_type -> banner.ResponseSlot
	5,  // 12: banner.BannerService.AddBanner:output_type -> banner.ResponseBanner
	5,  // 13: banner.BannerService.GetBanner:output_type -> banner.ResponseBanner
	8,  // 14: banner.BannerService.AddGroup:output_type -> banner.ResponseGroup
	8,  // 15: banner.BannerService.GetGroup:output_type -> banner.ResponseGroup
	11, // 16: banner.BannerService.AddBannerGroupStats:output_type -> banner.ResponseBannerGroupStats
	11, // 17: banner.BannerService.GetBannerGroupStats:output_type -> banner.ResponseBannerGroupStats
	13, // 18: banner.BannerService.RegisterClick:output_type -> banner.ResponseRegisterClick
	5,  // 19: banner.BannerService.GetBannerByMultiArmBandit:output_type -> banner.ResponseBanner
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_BannerService_proto_init() }
func file_BannerService_proto_init() {
	if File_BannerService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BannerService_proto_rawDesc), len(file_BannerService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BannerService_proto_goTypes,
		DependencyIndexes: file_BannerService_proto_depIdxs,
		MessageInfos:      file_BannerService_proto_msgTypes,
	}.Build()
	File_BannerService_proto = out.File
	file_BannerService_proto_goTypes = nil
	file_BannerService_proto_depIdxs = nil
}
